// Code generated by "stringer -type=TokenTag tokentag.go"; DO NOT EDIT.

package gosc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InvalidToken-0]
	_ = x[EOFToken-1]
	_ = x[LeftParanToken-2]
	_ = x[RightParenToken-3]
	_ = x[QuoteToken-4]
	_ = x[DotToken-5]
	_ = x[SymbolToken-6]
	_ = x[StringToken-7]
	_ = x[AtomToken-8]
}

const _TokenTag_name = "InvalidTokenEOFTokenLeftParanTokenRightParenTokenQuoteTokenDotTokenSymbolTokenStringTokenAtomToken"

var _TokenTag_index = [...]uint8{0, 12, 20, 34, 49, 59, 67, 78, 89, 98}

func (i TokenTag) String() string {
	if i < 0 || i >= TokenTag(len(_TokenTag_index)-1) {
		return "TokenTag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenTag_name[_TokenTag_index[i]:_TokenTag_index[i+1]]
}
